CREATE TABLE dorp (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, naam VARCHAR(30) DEFAULT NULL, img VARCHAR(30) NOT NULL DEFAULT '/img/dorpen/default.jpg', updated_at DATE DEFAULT NULL, created_at DATE DEFAULT NULL);

CREATE TABLE evenement (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, naam VARCHAR(255) DEFAULT NULL, dorp_id INT(11) NOT NULL, img VARCHAR(255) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, created_at DATE DEFAULT NULL, updated_at DATE DEFAULT NULL);

CREATE TABLE imagemanager (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, img VARCHAR(255) NOT NULL, dorp_id INT(11) DEFAULT NULL, evenement_id INT(11) DEFAULT NULL, updated_at DATE NOT NULL, created_at DATE NOT NULL);

CREATE TABLE link (id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY, evenement_id INT(11) NOT NULL, link VARCHAR(255) NOT NULL, naam VARCHAR(255) NOT NULL, updated_at DATE NOT NULL, created_at DATE NOT NULL);

CREATE TABLE migrations (id INT(10) UNSIGNED NOT NULL, migration VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, batch INT(11) NOT NULL);

CREATE TABLE password_resets (email VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, token VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, created_at timestamp NULL DEFAULT NULL);

CREATE TABLE users (id INT(10) UNSIGNED NOT NULL, name VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, email VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, password VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL, remember_token VARCHAR(100) COLLATE utf8_unicode_ci DEFAULT NULL, created_at timestamp NULL DEFAULT NULL, updated_at timestamp NULL DEFAULT NULL);